# Albator macOS Hardening Configuration
# Central configuration file for all security hardening operations

# Application settings
app:
  name: "Albator"
  version: "2.1.0"
  author: "Cyberdyne Systems"
  
# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  directory: "/tmp/albator_logs"
  max_file_size: "10MB"
  backup_count: 5
  enable_json_logging: true
  enable_audit_trail: true

# Security profiles
profiles:
  basic:
    description: "Essential security for general users"
    settings:
      firewall:
        enabled: true
        stealth_mode: true
        block_all_incoming: false
        logging: true
      privacy:
        disable_siri_analytics: true
        disable_crash_reporting: true
        disable_safari_suggestions: true
        disable_diagnostic_reports: true
      encryption:
        enable_filevault: false  # Requires user interaction
      app_security:
        enable_gatekeeper: true
        verify_hardened_runtime: true
      system:
        disable_guest_account: true
        require_screensaver_password: true
        enable_automatic_updates: true
        disable_ssh: true
        disable_remote_management: true
  
  advanced:
    description: "Enhanced security for power users"
    inherits: "basic"
    settings:
      firewall:
        block_all_incoming: true
        advanced_logging: true
      privacy:
        disable_location_services: true
        disable_personalized_ads: true
        disable_handoff: true
      encryption:
        enable_filevault: true
        secure_boot: true
      system:
        disable_bluetooth: false  # May impact usability
        lockdown_mode: false      # macOS 13+ feature
        secure_keyboard_entry: true
  
  enterprise:
    description: "Maximum security for organizations"
    inherits: "advanced"
    settings:
      firewall:
        strict_mode: true
        custom_rules: true
      privacy:
        disable_all_telemetry: true
        disable_cloud_sync: true
        disable_app_analytics: true
      encryption:
        force_filevault: true
        institutional_recovery_key: true
      system:
        disable_bluetooth: true
        lockdown_mode: true
        disable_wifi: false
        centralized_logging: true
        compliance_reporting: true

# Default profile to use
default_profile: "basic"

# Operation settings
operations:
  # Timeout for commands (in seconds)
  command_timeout: 300
  
  # Retry settings
  max_retries: 3
  retry_delay: 5
  
  # Backup settings
  create_backups: true
  backup_directory: "/tmp/albator_backups"
  
  # Validation settings
  validate_after_apply: true
  strict_validation: false
  
  # Progress reporting
  show_progress: true
  progress_update_interval: 1

# External dependencies
dependencies:
  required:
    - name: "curl"
      command: "curl --version"
      install_hint: "Usually pre-installed on macOS"
    - name: "sudo"
      command: "sudo -V"
      install_hint: "Administrator privileges required"
  
  recommended:
    - name: "jq"
      command: "jq --version"
      install_hint: "brew install jq"
    - name: "pup"
      command: "pup --version"
      install_hint: "brew install pup"
  
  optional:
    - name: "gh"
      command: "gh --version"
      install_hint: "brew install gh"

# Script-specific settings
scripts:
  privacy:
    dry_run_default: false
    backup_preferences: true
    show_changes: true
  
  firewall:
    test_connectivity: true
    backup_rules: true
    verify_settings: true
  
  encryption:
    check_prerequisites: true
    warn_about_reboot: true
    validate_recovery_key: true
  
  app_security:
    scan_applications: true
    report_unsigned_apps: true
    quarantine_unknown: false

# CVE and updates settings
security_feeds:
  cve:
    enabled: true
    api_url: "https://api.github.com/advisories"
    max_results: 50
    severity_filter: ["critical", "high", "medium"]
    cache_duration: 3600  # 1 hour
  
  apple_updates:
    enabled: true
    url: "https://support.apple.com/en-us/HT201222"
    check_interval: 86400  # 24 hours
    auto_download: false

# Reporting settings
reporting:
  formats: ["json", "html", "csv"]
  include_recommendations: true
  include_compliance_status: true
  output_directory: "/tmp/albator_reports"
  
  # Compliance frameworks
  compliance:
    nist_800_53: true
    cis_macos: true
    soc2: false
    custom_framework: false

# Web interface settings (if using web mode)
web:
  host: "127.0.0.1"
  port: 5000
  debug: false
  secret_key: "change-this-in-production"
  auth_required: true

# API settings
api:
  enabled: false
  host: "127.0.0.1"
  port: 8000
  rate_limiting: true
  max_requests_per_minute: 60

# Fleet management settings
fleet:
  enabled: false
  ssh_timeout: 30
  concurrent_operations: 5
  inventory_file: "fleet_inventory.json"

# Advanced features
advanced:
  # Machine learning features
  ml_predictions: false
  behavioral_analysis: false
  
  # Cloud integration
  cloud_sync: false
  cloud_provider: "aws"  # aws, azure, gcp
  
  # Zero trust features
  continuous_verification: false
  device_attestation: false
  
  # Threat detection
  real_time_monitoring: false
  ioc_scanning: false

# Notification settings
notifications:
  enabled: true
  methods: ["console", "log"]  # console, log, email, slack
  events: ["error", "critical", "operation_complete"]
  
  # Email settings (if email notifications enabled)
  email:
    smtp_host: ""
    smtp_port: 587
    username: ""
    password: ""
    from_address: ""
    to_addresses: []

# Environment-specific overrides
environments:
  development:
    logging:
      level: "DEBUG"
    operations:
      validate_after_apply: false
  
  testing:
    operations:
      create_backups: false
      dry_run_default: true
  
  production:
    logging:
      level: "WARNING"
    operations:
      strict_validation: true
      max_retries: 1